import Navbar from "./components/Navbar";
import "./globals.css";
// import "./Section1.css";
import { Montserrat, Poiret_One } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // multiple weights
  variable: "--font-montserrat",
});

const poiretOne = Poiret_One({
  subsets: ["latin"],
  weight: "400", // only available weight
  variable: "--font-poiret",
});

export const metadata = {
  title: "Astrix AI BOS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${montserrat.variable} ${poiretOne.variable}`}>
      <body className={"antialiased overflow-x-hidden"}>
        <header>
          <Navbar />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
